name: "Build index.json file"
on: [push]
jobs:
  build-index-json:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v2
      - name: Generate index.json
        run: ./build.py index.json
      - name: Commit files
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Bot: generate index.json"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
