name: "Build index.json file"
on: [push]
jobs:
  build-index-json:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v2
      - name: Generate index.json
        run: ./build.py index.json
      - name: Commit files
        id: commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.json
          if [[ "`git status --porcelain index.json`" ]]
          then
            git commit -m "Bot: generate index.json"
            echo "need push"
            echo "::set-output name=need-push::true"
          else
            echo "don't need push"
            echo "::set-output name=need-push::false"
          fi
      - name: Push changes
        if: steps.commit.outputs.need-push == true
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
